// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotificationStatus int32

const (
	NotificationStatus_Unknown              NotificationStatus = 0
	NotificationStatus_New                  NotificationStatus = 1
	NotificationStatus_Sent                 NotificationStatus = 2
	NotificationStatus_Completed            NotificationStatus = 3
	NotificationStatus_AutomaticallyHandled NotificationStatus = 4
)

var NotificationStatus_name = map[int32]string{
	0: "Unknown",
	1: "New",
	2: "Sent",
	3: "Completed",
	4: "AutomaticallyHandled",
}

var NotificationStatus_value = map[string]int32{
	"Unknown":              0,
	"New":                  1,
	"Sent":                 2,
	"Completed":            3,
	"AutomaticallyHandled": 4,
}

func (x NotificationStatus) String() string {
	return proto.EnumName(NotificationStatus_name, int32(x))
}

func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

type Link_LinkMethod int32

const (
	Link_GET     Link_LinkMethod = 0
	Link_HEAD    Link_LinkMethod = 1
	Link_POST    Link_LinkMethod = 2
	Link_PUT     Link_LinkMethod = 3
	Link_DELETE  Link_LinkMethod = 4
	Link_OPTIONS Link_LinkMethod = 5
	Link_PATCH   Link_LinkMethod = 6
)

var Link_LinkMethod_name = map[int32]string{
	0: "GET",
	1: "HEAD",
	2: "POST",
	3: "PUT",
	4: "DELETE",
	5: "OPTIONS",
	6: "PATCH",
}

var Link_LinkMethod_value = map[string]int32{
	"GET":     0,
	"HEAD":    1,
	"POST":    2,
	"PUT":     3,
	"DELETE":  4,
	"OPTIONS": 5,
	"PATCH":   6,
}

func (x Link_LinkMethod) String() string {
	return proto.EnumName(Link_LinkMethod_name, int32(x))
}

func (Link_LinkMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0, 0}
}

type NotificationItem_NotificationItemStatus int32

const (
	NotificationItem_New                  NotificationItem_NotificationItemStatus = 0
	NotificationItem_Accepted             NotificationItem_NotificationItemStatus = 1
	NotificationItem_Rejected             NotificationItem_NotificationItemStatus = 2
	NotificationItem_AutomaticallyHandled NotificationItem_NotificationItemStatus = 3
)

var NotificationItem_NotificationItemStatus_name = map[int32]string{
	0: "New",
	1: "Accepted",
	2: "Rejected",
	3: "AutomaticallyHandled",
}

var NotificationItem_NotificationItemStatus_value = map[string]int32{
	"New":                  0,
	"Accepted":             1,
	"Rejected":             2,
	"AutomaticallyHandled": 3,
}

func (x NotificationItem_NotificationItemStatus) String() string {
	return proto.EnumName(NotificationItem_NotificationItemStatus_name, int32(x))
}

func (NotificationItem_NotificationItemStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3, 0}
}

type RetryDetails_Reason int32

const (
	RetryDetails_Unspecified    RetryDetails_Reason = 0
	RetryDetails_ReprintRequest RetryDetails_Reason = 1
)

var RetryDetails_Reason_name = map[int32]string{
	0: "Unspecified",
	1: "ReprintRequest",
}

var RetryDetails_Reason_value = map[string]int32{
	"Unspecified":    0,
	"ReprintRequest": 1,
}

func (x RetryDetails_Reason) String() string {
	return proto.EnumName(RetryDetails_Reason_name, int32(x))
}

func (RetryDetails_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{5, 0}
}

type Notification_NotificationType int32

const (
	Notification_OrderRequest        Notification_NotificationType = 0
	Notification_CancellationRequest Notification_NotificationType = 1
	Notification_ChangeRequest       Notification_NotificationType = 2
	Notification_Unknown             Notification_NotificationType = 3
	Notification_ProductionStarted   Notification_NotificationType = 4
	Notification_ItemsRejected       Notification_NotificationType = 5
	Notification_Informational       Notification_NotificationType = 6
	Notification_RetryOrderRequest   Notification_NotificationType = 7
)

var Notification_NotificationType_name = map[int32]string{
	0: "OrderRequest",
	1: "CancellationRequest",
	2: "ChangeRequest",
	3: "Unknown",
	4: "ProductionStarted",
	5: "ItemsRejected",
	6: "Informational",
	7: "RetryOrderRequest",
}

var Notification_NotificationType_value = map[string]int32{
	"OrderRequest":        0,
	"CancellationRequest": 1,
	"ChangeRequest":       2,
	"Unknown":             3,
	"ProductionStarted":   4,
	"ItemsRejected":       5,
	"Informational":       6,
	"RetryOrderRequest":   7,
}

func (x Notification_NotificationType) String() string {
	return proto.EnumName(Notification_NotificationType_name, int32(x))
}

func (Notification_NotificationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{6, 0}
}

// [START messages]
type Link struct {
	Href                 string            `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	Methods              []Link_LinkMethod `protobuf:"varint,2,rep,packed,name=methods,proto3,enum=pb.Link_LinkMethod" json:"methods,omitempty"`
	Rel                  string            `protobuf:"bytes,3,opt,name=rel,proto3" json:"rel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetHref() string {
	if m != nil {
		return m.Href
	}
	return ""
}

func (m *Link) GetMethods() []Link_LinkMethod {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *Link) GetRel() string {
	if m != nil {
		return m.Rel
	}
	return ""
}

type Order struct {
	OrderId              string            `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Links                *Order_OrderLinks `protobuf:"bytes,2,opt,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetLinks() *Order_OrderLinks {
	if m != nil {
		return m.Links
	}
	return nil
}

type Order_OrderLinks struct {
	Self                 *Link    `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_OrderLinks) Reset()         { *m = Order_OrderLinks{} }
func (m *Order_OrderLinks) String() string { return proto.CompactTextString(m) }
func (*Order_OrderLinks) ProtoMessage()    {}
func (*Order_OrderLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1, 0}
}

func (m *Order_OrderLinks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_OrderLinks.Unmarshal(m, b)
}
func (m *Order_OrderLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_OrderLinks.Marshal(b, m, deterministic)
}
func (m *Order_OrderLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_OrderLinks.Merge(m, src)
}
func (m *Order_OrderLinks) XXX_Size() int {
	return xxx_messageInfo_Order_OrderLinks.Size(m)
}
func (m *Order_OrderLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_OrderLinks.DiscardUnknown(m)
}

var xxx_messageInfo_Order_OrderLinks proto.InternalMessageInfo

func (m *Order_OrderLinks) GetSelf() *Link {
	if m != nil {
		return m.Self
	}
	return nil
}

type Fulfiller struct {
	Links                *Fulfiller_FulfillerLinks `protobuf:"bytes,1,opt,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Fulfiller) Reset()         { *m = Fulfiller{} }
func (m *Fulfiller) String() string { return proto.CompactTextString(m) }
func (*Fulfiller) ProtoMessage()    {}
func (*Fulfiller) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{2}
}

func (m *Fulfiller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fulfiller.Unmarshal(m, b)
}
func (m *Fulfiller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fulfiller.Marshal(b, m, deterministic)
}
func (m *Fulfiller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fulfiller.Merge(m, src)
}
func (m *Fulfiller) XXX_Size() int {
	return xxx_messageInfo_Fulfiller.Size(m)
}
func (m *Fulfiller) XXX_DiscardUnknown() {
	xxx_messageInfo_Fulfiller.DiscardUnknown(m)
}

var xxx_messageInfo_Fulfiller proto.InternalMessageInfo

func (m *Fulfiller) GetLinks() *Fulfiller_FulfillerLinks {
	if m != nil {
		return m.Links
	}
	return nil
}

type Fulfiller_FulfillerLinks struct {
	Self                 *Link    `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fulfiller_FulfillerLinks) Reset()         { *m = Fulfiller_FulfillerLinks{} }
func (m *Fulfiller_FulfillerLinks) String() string { return proto.CompactTextString(m) }
func (*Fulfiller_FulfillerLinks) ProtoMessage()    {}
func (*Fulfiller_FulfillerLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{2, 0}
}

func (m *Fulfiller_FulfillerLinks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fulfiller_FulfillerLinks.Unmarshal(m, b)
}
func (m *Fulfiller_FulfillerLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fulfiller_FulfillerLinks.Marshal(b, m, deterministic)
}
func (m *Fulfiller_FulfillerLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fulfiller_FulfillerLinks.Merge(m, src)
}
func (m *Fulfiller_FulfillerLinks) XXX_Size() int {
	return xxx_messageInfo_Fulfiller_FulfillerLinks.Size(m)
}
func (m *Fulfiller_FulfillerLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_Fulfiller_FulfillerLinks.DiscardUnknown(m)
}

var xxx_messageInfo_Fulfiller_FulfillerLinks proto.InternalMessageInfo

func (m *Fulfiller_FulfillerLinks) GetSelf() *Link {
	if m != nil {
		return m.Self
	}
	return nil
}

type NotificationItem struct {
	ItemId               string                                  `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Status               NotificationItem_NotificationItemStatus `protobuf:"varint,2,opt,name=status,proto3,enum=pb.NotificationItem_NotificationItemStatus" json:"status,omitempty"`
	Links                *NotificationItem_NotificationItemLinks `protobuf:"bytes,3,opt,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *NotificationItem) Reset()         { *m = NotificationItem{} }
func (m *NotificationItem) String() string { return proto.CompactTextString(m) }
func (*NotificationItem) ProtoMessage()    {}
func (*NotificationItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3}
}

func (m *NotificationItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationItem.Unmarshal(m, b)
}
func (m *NotificationItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationItem.Marshal(b, m, deterministic)
}
func (m *NotificationItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationItem.Merge(m, src)
}
func (m *NotificationItem) XXX_Size() int {
	return xxx_messageInfo_NotificationItem.Size(m)
}
func (m *NotificationItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationItem.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationItem proto.InternalMessageInfo

func (m *NotificationItem) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *NotificationItem) GetStatus() NotificationItem_NotificationItemStatus {
	if m != nil {
		return m.Status
	}
	return NotificationItem_New
}

func (m *NotificationItem) GetLinks() *NotificationItem_NotificationItemLinks {
	if m != nil {
		return m.Links
	}
	return nil
}

type NotificationItem_NotificationItemLinks struct {
	Self                 *Link    `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Accept               *Link    `protobuf:"bytes,2,opt,name=accept,proto3" json:"accept,omitempty"`
	Reject               *Link    `protobuf:"bytes,3,opt,name=reject,proto3" json:"reject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationItem_NotificationItemLinks) Reset() {
	*m = NotificationItem_NotificationItemLinks{}
}
func (m *NotificationItem_NotificationItemLinks) String() string { return proto.CompactTextString(m) }
func (*NotificationItem_NotificationItemLinks) ProtoMessage()    {}
func (*NotificationItem_NotificationItemLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3, 0}
}

func (m *NotificationItem_NotificationItemLinks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationItem_NotificationItemLinks.Unmarshal(m, b)
}
func (m *NotificationItem_NotificationItemLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationItem_NotificationItemLinks.Marshal(b, m, deterministic)
}
func (m *NotificationItem_NotificationItemLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationItem_NotificationItemLinks.Merge(m, src)
}
func (m *NotificationItem_NotificationItemLinks) XXX_Size() int {
	return xxx_messageInfo_NotificationItem_NotificationItemLinks.Size(m)
}
func (m *NotificationItem_NotificationItemLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationItem_NotificationItemLinks.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationItem_NotificationItemLinks proto.InternalMessageInfo

func (m *NotificationItem_NotificationItemLinks) GetSelf() *Link {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *NotificationItem_NotificationItemLinks) GetAccept() *Link {
	if m != nil {
		return m.Accept
	}
	return nil
}

func (m *NotificationItem_NotificationItemLinks) GetReject() *Link {
	if m != nil {
		return m.Reject
	}
	return nil
}

type ChangeRequest struct {
	DeliveryChangeDetails *ChangeRequest_DeliveryChange `protobuf:"bytes,1,opt,name=deliveryChangeDetails,proto3" json:"deliveryChangeDetails,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                      `json:"-"`
	XXX_unrecognized      []byte                        `json:"-"`
	XXX_sizecache         int32                         `json:"-"`
}

func (m *ChangeRequest) Reset()         { *m = ChangeRequest{} }
func (m *ChangeRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeRequest) ProtoMessage()    {}
func (*ChangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{4}
}

func (m *ChangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRequest.Unmarshal(m, b)
}
func (m *ChangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRequest.Marshal(b, m, deterministic)
}
func (m *ChangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRequest.Merge(m, src)
}
func (m *ChangeRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeRequest.Size(m)
}
func (m *ChangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRequest proto.InternalMessageInfo

func (m *ChangeRequest) GetDeliveryChangeDetails() *ChangeRequest_DeliveryChange {
	if m != nil {
		return m.DeliveryChangeDetails
	}
	return nil
}

type ChangeRequest_DeliveryChange struct {
	DestinationAddress   *ChangeRequest_DeliveryChange_AddressChange `protobuf:"bytes,1,opt,name=destinationAddress,proto3" json:"destinationAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *ChangeRequest_DeliveryChange) Reset()         { *m = ChangeRequest_DeliveryChange{} }
func (m *ChangeRequest_DeliveryChange) String() string { return proto.CompactTextString(m) }
func (*ChangeRequest_DeliveryChange) ProtoMessage()    {}
func (*ChangeRequest_DeliveryChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{4, 0}
}

func (m *ChangeRequest_DeliveryChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRequest_DeliveryChange.Unmarshal(m, b)
}
func (m *ChangeRequest_DeliveryChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRequest_DeliveryChange.Marshal(b, m, deterministic)
}
func (m *ChangeRequest_DeliveryChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRequest_DeliveryChange.Merge(m, src)
}
func (m *ChangeRequest_DeliveryChange) XXX_Size() int {
	return xxx_messageInfo_ChangeRequest_DeliveryChange.Size(m)
}
func (m *ChangeRequest_DeliveryChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRequest_DeliveryChange.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRequest_DeliveryChange proto.InternalMessageInfo

func (m *ChangeRequest_DeliveryChange) GetDestinationAddress() *ChangeRequest_DeliveryChange_AddressChange {
	if m != nil {
		return m.DestinationAddress
	}
	return nil
}

type ChangeRequest_DeliveryChange_AddressChange struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode           string   `protobuf:"bytes,2,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	StateOrProvince      string   `protobuf:"bytes,3,opt,name=stateOrProvince,proto3" json:"stateOrProvince,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Company              string   `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	FirstName            string   `protobuf:"bytes,6,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,7,opt,name=lastName,proto3" json:"lastName,omitempty"`
	MiddleName           string   `protobuf:"bytes,8,opt,name=middleName,proto3" json:"middleName,omitempty"`
	Phone                string   `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	PhoneExt             string   `protobuf:"bytes,10,opt,name=phoneExt,proto3" json:"phoneExt,omitempty"`
	Street1              string   `protobuf:"bytes,11,opt,name=street1,proto3" json:"street1,omitempty"`
	Street2              string   `protobuf:"bytes,12,opt,name=street2,proto3" json:"street2,omitempty"`
	Email                string   `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`
	DoorCode             string   `protobuf:"bytes,14,opt,name=doorCode,proto3" json:"doorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeRequest_DeliveryChange_AddressChange) Reset() {
	*m = ChangeRequest_DeliveryChange_AddressChange{}
}
func (m *ChangeRequest_DeliveryChange_AddressChange) String() string {
	return proto.CompactTextString(m)
}
func (*ChangeRequest_DeliveryChange_AddressChange) ProtoMessage() {}
func (*ChangeRequest_DeliveryChange_AddressChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{4, 0, 0}
}

func (m *ChangeRequest_DeliveryChange_AddressChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRequest_DeliveryChange_AddressChange.Unmarshal(m, b)
}
func (m *ChangeRequest_DeliveryChange_AddressChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRequest_DeliveryChange_AddressChange.Marshal(b, m, deterministic)
}
func (m *ChangeRequest_DeliveryChange_AddressChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRequest_DeliveryChange_AddressChange.Merge(m, src)
}
func (m *ChangeRequest_DeliveryChange_AddressChange) XXX_Size() int {
	return xxx_messageInfo_ChangeRequest_DeliveryChange_AddressChange.Size(m)
}
func (m *ChangeRequest_DeliveryChange_AddressChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRequest_DeliveryChange_AddressChange.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRequest_DeliveryChange_AddressChange proto.InternalMessageInfo

func (m *ChangeRequest_DeliveryChange_AddressChange) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetStateOrProvince() string {
	if m != nil {
		return m.StateOrProvince
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetPhoneExt() string {
	if m != nil {
		return m.PhoneExt
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetStreet1() string {
	if m != nil {
		return m.Street1
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetStreet2() string {
	if m != nil {
		return m.Street2
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChangeRequest_DeliveryChange_AddressChange) GetDoorCode() string {
	if m != nil {
		return m.DoorCode
	}
	return ""
}

type RetryDetails struct {
	Reason               RetryDetails_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=pb.RetryDetails_Reason" json:"reason,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RetryDetails) Reset()         { *m = RetryDetails{} }
func (m *RetryDetails) String() string { return proto.CompactTextString(m) }
func (*RetryDetails) ProtoMessage()    {}
func (*RetryDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{5}
}

func (m *RetryDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryDetails.Unmarshal(m, b)
}
func (m *RetryDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryDetails.Marshal(b, m, deterministic)
}
func (m *RetryDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryDetails.Merge(m, src)
}
func (m *RetryDetails) XXX_Size() int {
	return xxx_messageInfo_RetryDetails.Size(m)
}
func (m *RetryDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryDetails.DiscardUnknown(m)
}

var xxx_messageInfo_RetryDetails proto.InternalMessageInfo

func (m *RetryDetails) GetReason() RetryDetails_Reason {
	if m != nil {
		return m.Reason
	}
	return RetryDetails_Unspecified
}

func (m *RetryDetails) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Notification struct {
	NotificationId       string                          `protobuf:"bytes,1,opt,name=notificationId,proto3" json:"notificationId,omitempty"`
	Type                 Notification_NotificationType   `protobuf:"varint,2,opt,name=type,proto3,enum=pb.Notification_NotificationType" json:"type,omitempty"`
	Status               NotificationStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=pb.NotificationStatus" json:"status,omitempty"`
	CreatedDate          string                          `protobuf:"bytes,4,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	Order                *Order                          `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	Fulfiller            *Fulfiller                      `protobuf:"bytes,6,opt,name=fulfiller,proto3" json:"fulfiller,omitempty"`
	Items                []*NotificationItem             `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	Links                *Notification_NotificationLinks `protobuf:"bytes,8,opt,name=links,proto3" json:"links,omitempty"`
	ChangeRequest        *ChangeRequest                  `protobuf:"bytes,9,opt,name=changeRequest,proto3" json:"changeRequest,omitempty"`
	RetryOrderRequest    *RetryDetails                   `protobuf:"bytes,10,opt,name=retryOrderRequest,proto3" json:"retryOrderRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{6}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetNotificationId() string {
	if m != nil {
		return m.NotificationId
	}
	return ""
}

func (m *Notification) GetType() Notification_NotificationType {
	if m != nil {
		return m.Type
	}
	return Notification_OrderRequest
}

func (m *Notification) GetStatus() NotificationStatus {
	if m != nil {
		return m.Status
	}
	return NotificationStatus_Unknown
}

func (m *Notification) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *Notification) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *Notification) GetFulfiller() *Fulfiller {
	if m != nil {
		return m.Fulfiller
	}
	return nil
}

func (m *Notification) GetItems() []*NotificationItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Notification) GetLinks() *Notification_NotificationLinks {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Notification) GetChangeRequest() *ChangeRequest {
	if m != nil {
		return m.ChangeRequest
	}
	return nil
}

func (m *Notification) GetRetryOrderRequest() *RetryDetails {
	if m != nil {
		return m.RetryOrderRequest
	}
	return nil
}

type Notification_NotificationLinks struct {
	Self                 *Link    `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Accept               *Link    `protobuf:"bytes,2,opt,name=accept,proto3" json:"accept,omitempty"`
	Reject               *Link    `protobuf:"bytes,3,opt,name=reject,proto3" json:"reject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification_NotificationLinks) Reset()         { *m = Notification_NotificationLinks{} }
func (m *Notification_NotificationLinks) String() string { return proto.CompactTextString(m) }
func (*Notification_NotificationLinks) ProtoMessage()    {}
func (*Notification_NotificationLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{6, 0}
}

func (m *Notification_NotificationLinks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification_NotificationLinks.Unmarshal(m, b)
}
func (m *Notification_NotificationLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification_NotificationLinks.Marshal(b, m, deterministic)
}
func (m *Notification_NotificationLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification_NotificationLinks.Merge(m, src)
}
func (m *Notification_NotificationLinks) XXX_Size() int {
	return xxx_messageInfo_Notification_NotificationLinks.Size(m)
}
func (m *Notification_NotificationLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification_NotificationLinks.DiscardUnknown(m)
}

var xxx_messageInfo_Notification_NotificationLinks proto.InternalMessageInfo

func (m *Notification_NotificationLinks) GetSelf() *Link {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *Notification_NotificationLinks) GetAccept() *Link {
	if m != nil {
		return m.Accept
	}
	return nil
}

func (m *Notification_NotificationLinks) GetReject() *Link {
	if m != nil {
		return m.Reject
	}
	return nil
}

type Notifications struct {
	Notification         []*Notification `protobuf:"bytes,1,rep,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Notifications) Reset()         { *m = Notifications{} }
func (m *Notifications) String() string { return proto.CompactTextString(m) }
func (*Notifications) ProtoMessage()    {}
func (*Notifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{7}
}

func (m *Notifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notifications.Unmarshal(m, b)
}
func (m *Notifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notifications.Marshal(b, m, deterministic)
}
func (m *Notifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notifications.Merge(m, src)
}
func (m *Notifications) XXX_Size() int {
	return xxx_messageInfo_Notifications.Size(m)
}
func (m *Notifications) XXX_DiscardUnknown() {
	xxx_messageInfo_Notifications.DiscardUnknown(m)
}

var xxx_messageInfo_Notifications proto.InternalMessageInfo

func (m *Notifications) GetNotification() []*Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.NotificationStatus", NotificationStatus_name, NotificationStatus_value)
	proto.RegisterEnum("pb.Link_LinkMethod", Link_LinkMethod_name, Link_LinkMethod_value)
	proto.RegisterEnum("pb.NotificationItem_NotificationItemStatus", NotificationItem_NotificationItemStatus_name, NotificationItem_NotificationItemStatus_value)
	proto.RegisterEnum("pb.RetryDetails_Reason", RetryDetails_Reason_name, RetryDetails_Reason_value)
	proto.RegisterEnum("pb.Notification_NotificationType", Notification_NotificationType_name, Notification_NotificationType_value)
	proto.RegisterType((*Link)(nil), "pb.Link")
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*Order_OrderLinks)(nil), "pb.Order.OrderLinks")
	proto.RegisterType((*Fulfiller)(nil), "pb.Fulfiller")
	proto.RegisterType((*Fulfiller_FulfillerLinks)(nil), "pb.Fulfiller.FulfillerLinks")
	proto.RegisterType((*NotificationItem)(nil), "pb.NotificationItem")
	proto.RegisterType((*NotificationItem_NotificationItemLinks)(nil), "pb.NotificationItem.NotificationItemLinks")
	proto.RegisterType((*ChangeRequest)(nil), "pb.ChangeRequest")
	proto.RegisterType((*ChangeRequest_DeliveryChange)(nil), "pb.ChangeRequest.DeliveryChange")
	proto.RegisterType((*ChangeRequest_DeliveryChange_AddressChange)(nil), "pb.ChangeRequest.DeliveryChange.AddressChange")
	proto.RegisterType((*RetryDetails)(nil), "pb.RetryDetails")
	proto.RegisterType((*Notification)(nil), "pb.Notification")
	proto.RegisterType((*Notification_NotificationLinks)(nil), "pb.Notification.NotificationLinks")
	proto.RegisterType((*Notifications)(nil), "pb.Notifications")
}

func init() { proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07) }

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 1068 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0xce, 0xc4, 0x9e, 0xbf, 0x9a, 0x9f, 0xed, 0xd4, 0x6e, 0xb2, 0x56, 0x14, 0xc1, 0xe0, 0x03,
	0x8a, 0xb2, 0xda, 0x41, 0x18, 0x10, 0x9c, 0x10, 0xd1, 0x64, 0x20, 0x91, 0x96, 0x64, 0xe4, 0x4c,
	0x96, 0x13, 0x48, 0x8e, 0x5d, 0xb3, 0x31, 0xf1, 0x1f, 0xed, 0x9e, 0x5d, 0xe6, 0x01, 0x40, 0xdc,
	0x39, 0xf0, 0x1c, 0x88, 0x17, 0xe3, 0x11, 0x50, 0xb7, 0xed, 0x19, 0xdb, 0x13, 0x76, 0x39, 0x71,
	0xb1, 0xba, 0xaa, 0xbe, 0xea, 0xaa, 0xea, 0xae, 0xfe, 0xca, 0x80, 0x51, 0x2c, 0xfc, 0x85, 0xef,
	0x3a, 0xc2, 0x8f, 0xa3, 0x71, 0xc2, 0x63, 0x11, 0xe3, 0x6e, 0x72, 0x6b, 0xfe, 0xd5, 0x00, 0xfd,
	0x85, 0x1f, 0xdd, 0x23, 0x82, 0x7e, 0xc7, 0x69, 0x61, 0x34, 0x46, 0x8d, 0xe3, 0xae, 0xad, 0xd6,
	0xf8, 0x1c, 0xda, 0x21, 0x89, 0xbb, 0xd8, 0x4b, 0x8d, 0xdd, 0x91, 0x76, 0x3c, 0xb4, 0x1e, 0x8f,
	0x93, 0xdb, 0xb1, 0x84, 0xab, 0xcf, 0xb7, 0xca, 0x66, 0x17, 0x18, 0x64, 0xa0, 0x71, 0x0a, 0x0c,
	0x4d, 0xed, 0x20, 0x97, 0xe6, 0x4b, 0x80, 0x0d, 0x10, 0xdb, 0xa0, 0x7d, 0x33, 0x9d, 0xb3, 0x1d,
	0xec, 0x80, 0x7e, 0x3e, 0x3d, 0x3d, 0x63, 0x0d, 0xb9, 0x9a, 0x5d, 0x5d, 0xcf, 0xd9, 0xae, 0x34,
	0xce, 0x6e, 0xe6, 0x4c, 0x43, 0x80, 0xd6, 0xd9, 0xf4, 0xc5, 0x74, 0x3e, 0x65, 0x3a, 0xf6, 0xa0,
	0x7d, 0x35, 0x9b, 0x5f, 0x5c, 0x5d, 0x5e, 0xb3, 0x26, 0x76, 0xa1, 0x39, 0x3b, 0x9d, 0x4f, 0xce,
	0x59, 0xcb, 0x5c, 0x41, 0xf3, 0x8a, 0x7b, 0xc4, 0xd1, 0x80, 0x76, 0x2c, 0x17, 0x17, 0x5e, 0x9e,
	0x78, 0x21, 0xe2, 0x09, 0x34, 0x03, 0x3f, 0xba, 0x97, 0x99, 0x37, 0x8e, 0x7b, 0xd6, 0x13, 0x99,
	0xb9, 0xf2, 0xc9, 0xbe, 0x32, 0xad, 0xd4, 0xce, 0x20, 0x87, 0x27, 0x00, 0x1b, 0x25, 0x1e, 0x81,
	0x9e, 0x52, 0x90, 0x9d, 0x44, 0xcf, 0xea, 0x14, 0x25, 0xdb, 0x4a, 0x6b, 0xc6, 0xd0, 0xfd, 0x7a,
	0x19, 0x2c, 0xfc, 0x20, 0x20, 0x8e, 0x56, 0x11, 0x24, 0xc3, 0x1e, 0x49, 0xec, 0xda, 0xba, 0x59,
	0x55, 0x82, 0x8d, 0x61, 0x58, 0x35, 0xbc, 0x23, 0xe0, 0x2f, 0x1a, 0xb0, 0xcb, 0xd2, 0xe5, 0x5d,
	0x08, 0x0a, 0xf1, 0x00, 0x5a, 0xbe, 0xa0, 0x70, 0x5d, 0x76, 0x2e, 0xe1, 0x04, 0x5a, 0xa9, 0x70,
	0xc4, 0x32, 0x2b, 0x7b, 0x68, 0x3d, 0x93, 0x9b, 0xd5, 0xbd, 0xb7, 0x14, 0xd7, 0xca, 0xc5, 0xce,
	0x5d, 0xf1, 0xab, 0xa2, 0x2a, 0x4d, 0x25, 0x74, 0xf2, 0x9f, 0xf6, 0xa8, 0xd4, 0xb8, 0x82, 0xfd,
	0x07, 0xed, 0x6f, 0x2f, 0x15, 0x47, 0xd0, 0x72, 0x5c, 0x97, 0x12, 0x91, 0x5f, 0xda, 0xc6, 0x9e,
	0xeb, 0x25, 0x82, 0xd3, 0x8f, 0xe4, 0x8a, 0x3c, 0xb7, 0x12, 0x22, 0xd3, 0x9b, 0xdf, 0xc1, 0xc1,
	0xc3, 0xe5, 0xc9, 0x0e, 0xbb, 0xa4, 0x37, 0x6c, 0x07, 0xfb, 0xd0, 0x39, 0x55, 0xdb, 0x91, 0xc7,
	0x1a, 0x52, 0xb2, 0x95, 0x2b, 0x79, 0x6c, 0x17, 0x0d, 0x78, 0x72, 0xba, 0x14, 0x71, 0xe8, 0x08,
	0xdf, 0x75, 0x82, 0x60, 0x75, 0xee, 0x44, 0x5e, 0x40, 0x1e, 0xd3, 0xcc, 0xbf, 0x75, 0x18, 0x4c,
	0xee, 0x9c, 0xe8, 0x15, 0xd9, 0xf4, 0xd3, 0x92, 0x52, 0x81, 0x2f, 0x61, 0xdf, 0xa3, 0xc0, 0x7f,
	0x4d, 0x7c, 0x95, 0x19, 0xce, 0x48, 0x38, 0x7e, 0x50, 0x74, 0xc3, 0x48, 0xe6, 0x56, 0xf1, 0x18,
	0x9f, 0x55, 0xe0, 0xf6, 0xc3, 0xee, 0x87, 0xbf, 0xea, 0x30, 0xac, 0x22, 0xf1, 0x07, 0x40, 0x8f,
	0x52, 0xe1, 0x47, 0xaa, 0xa8, 0x53, 0xcf, 0xe3, 0x94, 0x16, 0x71, 0xc6, 0xef, 0x8a, 0x33, 0xce,
	0xf1, 0x39, 0xe6, 0x81, 0x9d, 0x0e, 0x7f, 0xd7, 0x60, 0x50, 0x41, 0xc9, 0x97, 0xe5, 0xc6, 0xcb,
	0x48, 0xf0, 0x55, 0xf1, 0xb2, 0x72, 0x11, 0xdf, 0x03, 0x48, 0xe2, 0x54, 0x38, 0xc1, 0x24, 0xf6,
	0x48, 0xdd, 0x54, 0xd7, 0x2e, 0x69, 0xf0, 0x18, 0x1e, 0xc9, 0x46, 0xa2, 0x2b, 0x3e, 0xe3, 0xf1,
	0x6b, 0x3f, 0x72, 0x29, 0xa7, 0x84, 0xba, 0x5a, 0x72, 0x8e, 0xeb, 0x8b, 0x95, 0xa1, 0x67, 0x9c,
	0x23, 0xd7, 0x59, 0xdc, 0x30, 0x71, 0xa2, 0x95, 0xd1, 0x2c, 0xe2, 0x2a, 0x11, 0x8f, 0xa0, 0xbb,
	0xf0, 0x79, 0x2a, 0x2e, 0x9d, 0x90, 0x8c, 0x96, 0xb2, 0x6d, 0x14, 0x78, 0x08, 0x9d, 0xc0, 0xc9,
	0x8d, 0x6d, 0x65, 0x5c, 0xcb, 0x32, 0xe3, 0xd0, 0xf7, 0xbc, 0x80, 0x94, 0xb5, 0x93, 0x65, 0xbc,
	0xd1, 0xe0, 0x13, 0x68, 0x26, 0x77, 0x71, 0x44, 0x46, 0x57, 0x99, 0x32, 0x41, 0xee, 0xa8, 0x16,
	0xd3, 0x9f, 0x85, 0x01, 0xd9, 0x8e, 0x85, 0x2c, 0xb3, 0x4c, 0x05, 0x27, 0x12, 0x1f, 0x1b, 0xbd,
	0x2c, 0xcb, 0x5c, 0xdc, 0x58, 0x2c, 0xa3, 0x5f, 0xb6, 0x58, 0x32, 0x0a, 0x85, 0x8e, 0x1f, 0x18,
	0x83, 0x2c, 0x8a, 0x12, 0x64, 0x14, 0x2f, 0x8e, 0xb9, 0x3a, 0xcb, 0x61, 0x16, 0xa5, 0x90, 0xcd,
	0xdf, 0x1a, 0xd0, 0xb7, 0x49, 0xf0, 0x55, 0xde, 0x19, 0xf8, 0x91, 0x6c, 0x7f, 0x27, 0x8d, 0x23,
	0x75, 0x27, 0x43, 0xeb, 0xa9, 0xbc, 0xfa, 0x32, 0x62, 0x6c, 0x2b, 0xb3, 0x9d, 0xc3, 0x64, 0x36,
	0x21, 0xa5, 0xa9, 0xf3, 0xaa, 0xb8, 0xa8, 0x42, 0x34, 0x9f, 0x43, 0x2b, 0xc3, 0xe2, 0x23, 0xe8,
	0xdd, 0x44, 0x69, 0x42, 0xae, 0xbf, 0xf0, 0xc9, 0x63, 0x3b, 0x88, 0x30, 0xb4, 0x29, 0xe1, 0x7e,
	0x24, 0xf2, 0x7e, 0x62, 0x0d, 0xf3, 0x8f, 0x16, 0xf4, 0xcb, 0xef, 0x0a, 0x3f, 0x84, 0x61, 0x79,
	0xa4, 0xac, 0x99, 0xa8, 0xa6, 0xc5, 0xcf, 0x40, 0x17, 0xab, 0x84, 0x72, 0x3e, 0xfa, 0xa0, 0xce,
	0x25, 0x15, 0x61, 0xbe, 0x4a, 0xc8, 0x56, 0x70, 0x1c, 0xaf, 0x89, 0x4c, 0x53, 0x8e, 0x07, 0x75,
	0xc7, 0x1a, 0x67, 0x8d, 0xa0, 0xe7, 0x72, 0x72, 0x04, 0x79, 0x67, 0x8e, 0xa0, 0xbc, 0xa3, 0xca,
	0x2a, 0x7c, 0x1f, 0x9a, 0x6a, 0x36, 0xa8, 0xb6, 0xea, 0x59, 0xdd, 0xf5, 0x40, 0xb0, 0x33, 0x3d,
	0x3e, 0x83, 0xee, 0xa2, 0x20, 0x66, 0xd5, 0x5f, 0x3d, 0x6b, 0x50, 0x21, 0x74, 0x7b, 0x63, 0x97,
	0xe3, 0x45, 0x52, 0x6e, 0x6a, 0xb4, 0x47, 0x5a, 0x31, 0x5e, 0xea, 0xbc, 0x63, 0x67, 0x10, 0xfc,
	0xa2, 0xe0, 0xd3, 0x8e, 0xda, 0xd4, 0x7c, 0xeb, 0x19, 0x94, 0x79, 0x14, 0x3f, 0x87, 0x81, 0x5b,
	0x7e, 0xd8, 0xaa, 0x41, 0x7b, 0xd6, 0xde, 0xd6, 0x8b, 0xb7, 0xab, 0x38, 0xfc, 0x12, 0xf6, 0xb8,
	0x6c, 0x8b, 0xac, 0xc0, 0xdc, 0x19, 0x94, 0x33, 0xab, 0xf7, 0x8c, 0xbd, 0x0d, 0x3d, 0x5c, 0xc2,
	0xde, 0x56, 0x52, 0xff, 0x03, 0x79, 0xff, 0xd9, 0xa8, 0xce, 0x3a, 0xd9, 0x10, 0xc8, 0xa0, 0x5f,
	0xce, 0x8d, 0xed, 0xe0, 0x53, 0x78, 0x3c, 0x71, 0x22, 0x97, 0x82, 0x40, 0xa1, 0xd6, 0x5d, 0x8a,
	0x7b, 0x35, 0x8a, 0x66, 0xbb, 0xf2, 0x17, 0xe2, 0x26, 0xba, 0x8f, 0xe2, 0x37, 0x11, 0xd3, 0x70,
	0x1f, 0xf6, 0x66, 0x3c, 0xf6, 0x96, 0x6e, 0xde, 0x41, 0x5c, 0x92, 0xbe, 0x2e, 0xdd, 0xe4, 0x7d,
	0xa5, 0xeb, 0x39, 0xd0, 0x54, 0xaa, 0x68, 0x11, 0xf3, 0x50, 0x45, 0x70, 0x02, 0xd6, 0x92, 0xce,
	0x76, 0xfd, 0xa0, 0x58, 0xdb, 0x9c, 0xc2, 0xa0, 0x9c, 0x72, 0x8a, 0x9f, 0x42, 0xbf, 0xfc, 0x06,
	0x8c, 0x86, 0xea, 0x10, 0x56, 0xbf, 0x75, 0xbb, 0x82, 0x3a, 0xf9, 0x1e, 0x70, 0xbb, 0xbd, 0xcb,
	0xd9, 0xef, 0x14, 0x03, 0x4c, 0xfd, 0x35, 0x5d, 0x53, 0x24, 0xab, 0x1b, 0x40, 0x77, 0x12, 0x87,
	0x49, 0x40, 0x32, 0x6b, 0xed, 0x5f, 0xa7, 0x97, 0x7e, 0xdb, 0x52, 0xbf, 0x7c, 0x9f, 0xfc, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xb1, 0xff, 0x59, 0x7f, 0x08, 0x0a, 0x00, 0x00,
}
